language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script:
  - "flake8 . --config=flake8"
script: "coverage run --source=image_dump manage.py test"
after_success: coveralls
sudo: false
