#!/bin/bash

DJANGODIR=/srv/sites/danux_ninja/src/                # Django project directory
DJANGO_SETTINGS_MODULE=settings                      # which settings file should Django use
PYTHON_BIN_DIR=/srv/sites/danux_ninja/.virtualenvs/danux_ninja

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source $PYTHON_BIN_DIR/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
celery -A image_dump worker -B --loglevel=info
