#!/bin/bash

NAME="danux_ninja"                                   # Name of the application
DJANGODIR=/srv/sites/danux_ninja/src/                # Django project directory
SOCKFILE=/srv/sites/danux_ninja/run/gunicorn.sock    # we will communicte using this unix socket
USER=danux_ninja                                     # the user to run as
GROUP=webapps                                           # the group to run as
NUM_WORKERS=3                                          # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=settings                         # which settings file should Django use
DJANGO_WSGI_MODULE=app.wsgi # WSGI module name
PYTHON_BIN_DIR=/srv/sites/danux_ninja/.virtualenvs/danux_ninja
LOG=/srv/sites/danux_ninja/logs/gunicorn.log         # Log file

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source $PYTHON_BIN_DIR/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
rm -f $SOCKFILE
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $PYTHON_BIN_DIR/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=warn \
--log-file=$LOG
