# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_uploaded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
